// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLE5tsCZjIPDyYQ6xuMxdukjwYEhw5XV4',
    appId: '1:128636567777:android:dadcac3cbdb0322beaf7a0',
    messagingSenderId: '128636567777',
    projectId: 'recipe-app-4fd50',
    storageBucket: 'recipe-app-4fd50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoAEgDLc8z3q5bjaNNkFqwTye_AiZ1zpc',
    appId: '1:128636567777:ios:96ecd366901603adeaf7a0',
    messagingSenderId: '128636567777',
    projectId: 'recipe-app-4fd50',
    storageBucket: 'recipe-app-4fd50.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBED2iL5kJ7S33fyhRdDIug3cdzmNTymxQ',
    appId: '1:128636567777:web:1a3c6201d13375fbeaf7a0',
    messagingSenderId: '128636567777',
    projectId: 'recipe-app-4fd50',
    authDomain: 'recipe-app-4fd50.firebaseapp.com',
    storageBucket: 'recipe-app-4fd50.firebasestorage.app',
    measurementId: 'G-9SK78FWCD1',
  );
}
